In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd

2025-02-27 10:14:19.252760: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-27 10:14:19.273399: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1740631459.297480 4031430 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1740631459.304568 4031430 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-27 10:14:19.328830: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
from tqdm import tqdm
from transformers import BertTokenizerFast, AutoTokenizer
from datasets import load_dataset
import glob

In [4]:
tamil_file = "Tamil_Corpus_Cleaned.txt"

with open(tamil_file, encoding='utf-8') as f:  
    print(f.read(5000))

ஒலிம்பிக் போட்டிகள் நடந்த இடங்கள் 1. 1896 - ஏதென்ஸ், கிரீஸ் 2. 1900 - பாரிஸ், பிரான்ஸ் 3. 1904 - செயின் லூயிஸ், அமெரிக்கா 4. 1908 - லண்டன்,பிரிட்டன் 5. 1912 - ஸ்டோக்ஹோம், சுவீடன் 6. 1920 - ஆண்ட்வெர்ப், பெல்ஜியம் 7. 1924 - பாரிஸ், பிரான்ஸ் 8. 1928 - ஆம்ஸ்டர்டாம், ஹாலந்து 9. 1932 - லாஸ், ஏஞ்சல்ஸ் 10. 1936 - பெர்லின், ஜெர்மனி 11. 1948 - லண்டன், இங்கிலாந்து 12. 1952 - ஹல்சின்கி, பின்லாந்து 13. 1956 - மேபோர்ன்,ஆஸ்திரேலியா 14. 1960 - ரோம், இத்தாலி 15. 1964 - டோக்கியோ, ஜப்பான் 16. 1968 - மெக்சிகோ, மெக்ஸிக்கோ 17. 1972 - மியூனிக், ஜெர்மனி 18. 1976 - மான்ட்ரியல், கனடா 19. 1980 - மாஸ்கோ, USSR 20. 1984 - லாஸ் ஏஞ்சல்ஸ், அமெரிக்கா 21. 1988 - சியோல், தென் கொரியா 22. 1992 - பார்சிலோனா, ஸ்பெயின் 23. 1996 - அட்லாண்டா, அமெரிக்கா 24. 2000 - சிட்னி, ஆஸ்திரேலியா 25. 2004 - ஏதென்ஸ், கிரீஸ் 26. 2008 - பீஜிங், சீனா 27. 2012 - லண்டன், இங்கிலாந்து 28. 2016 - ரியோ, பிரேசில் 29. 2020 - டோக்கியோ, ஜப்பான் 30. 2024 - பாரிஸ், பிரான்ஸ் 31. 2028 - லாஸ் ஏஞ்சல்ஸ், அமெரிக்கா Music ncs:
இன்னும் வாழ்வதில் நம்பிக்கையற்றுப்போன குடும்பத்தின் எஞ்சிய உருப்படி இவன்தான். கடுமையான எறிகணைத் தாக்குதலொன்றில் இந்த 19வயது இளைஞனும் இவனது குடும்பத்து உறுப்பினர்கள் யாவரும் காயமடைந்து போனார்கள். இனி வாழ்வில்லை ஒன்றாய் யாவரும் பிணமாகப் போகிறோம் என்ற நினைவில் இரத்த வெள்ளத்தில் கிடந்தார்கள். கையையிழந்த தந்தை கையில் காயங்களுடன் அண்ணன் வயிற்றில் காயத்தோடு தங்கை கையிலும் காலிலும் காயத்தோடு தம்பி உடலில் எறிகணைச் சிதறல்களை ஏந்திய அம்மாவென குடும்பத்தில் சற்றுக் குறைந்த காயத்தோட ஆரோக்கியமானது இவன் ஒருவன் மட்டும்தான்.
20வயதில் போராளியாகி 20 வயதிலே களமொன்றில் காயமடைந்து இடுப்பின் கீழ் உணர்வுகள் இழந்த போதும் , தான் நேசித்த மண்ணுக்காகத் தனது ஆற்றல் முழுவதையும் அர்ப்பணித்து 2009 மே17, வரையும் களத்தில் கடைசி மூச்சையும் அர்ப்பணிக்கும் முடிவோடு காத்திருந்தவன். நிலமைகள் நினைத்தவற்றுக்கு மாறாக தலைகீழாகி இவனதும் இவன் போன்ற ஆயிரமாயிரம் பேரினதும் கனவுகளில் துரோகங்கள் வென்றுவிட தோற்றுப்போனது தமிழினம். கண்ணீரோடு கடைசியாக முள்ளிவாய்க்காலிலிருந்து இவனை இவனது தங்கைகள் காத்துக் கொண்டு போனார்கள். இவனை தடுப்பில் அடைத்தார்கள். மே16
17.09.10 அன்று கிளிநொச்சி கனகபுரம் மகாவித்தியாலயத்தில் கல்விகற்கும் 13பெற்றோரை இழந்த மாணவர்களுக்கான முதற்கட்ட உதவி வழங்கப்பட்டுள்ளது. சுதாகரன் கோபிகா , விஜயகுமார் மதுசா ,வைகுந்தவாசம் வாசுகி, தேவசிகாமணி வக்சாயினி, மகாதேவன் மோகனன், சுப்பிரமணியம் சுகந்தினி, பிரான்சிஸ் றைசன், அழகுதேவன் தமிழ்ச்செல்வி, ஜெகராசா குணாளன் ஜெகராசா கலைமகள், வில்வராசா குகேந்தினி, செல்வகுமார் சங்கீதா, மகாதேவன் துசாந்தி ஆகிய 13 மாணவர்களுக்கு ஆளுக்கு தலா இலங்கை ரூபா 1500ரூபா (ஆயிரத்து ஐந்நூறுரூபா) பணமாக வழங்கப்பட்டுள்ளது. இந்த நிதியானது மாணவர்களின் மாதாந்த
தாயகத்தை நேசித்த தாயகத்துக்காய் இரத்த உறவுகளை உடன் பிறந்த சகோதரர்களையெல்லாம் கொடுத்துவிட்டு இன்று அடுத்த நேரச் சோற்றுக்கே வழியின்றித் தவிக்கும் ஒரு குடும்பத்தின் தலைவனின் கதைகளிலிருந்து சிலதுளிகள் நேயர்களே உங்களுக்காக.!
கிளிநொச்சி செல்வாநகர் குடியிருப்பில் வாழ்கின்ற 10குடும்பங்களுக்கான உதவிகள் 14.09.10 அன்று வழங்கப்பட்டுள்ளது. இயற்கை அனர்த்தங்களாலும் போரினாலும் பாதிக்கப்பட்ட மேற்படி குடும்பங்களுக்கான சுயதொழில் ஊக்குவிப்புக்கான உதவிகளும் பிள்ளைகளின் கல்விக்கான உதவிகளும் வழங்கப்பட்டது. இக்குடும்பங்களைச் சேர்ந்த அனைவரும் அங்கவீனர்களாகவும் போரில் பிள்ளைகளை கணவர்களை இழந்தவர்களாகவும் மற்றும் தடுப்புமுகாமிலிருந்து வெளிவந்தவர்களாகவும் இருக்கின்றனர். இன்னும் தங்கள் உடல்களில் சன்னங்கள் எறிகணைத்துண்டுகளையும் சுமந்து கொண்டிருக்கும் இவர்களை நம்பிக்கைகொடுத்துப் புதுப்பிக்கும் உதவியாக இவ்வுதவிகள் வழங்கப்பட்டுள்ளது. கூரைகள் அற்ற வீடுகளில் தறப்பாள்களோடு வாழ்கின்ற இம்மக்கள் தங்களுக்கான தொழில்
கனவாயிருந்த ஊருக்குள் காலடி வைத்திருக்கும் சாந்தபுரம் மக்களின் நிலமையென்ன ? விளக்குகிறார் தீபச்செல்வன்.
யுத்தத்தின் கடைசிக் காலங்களில் மகளைத்தேடித் தேடியே தேய்ந்து போன நம்பிக்கை மீறித் தன்மகளை இந்தத்தாய் தேடிக்கொண்டிருந்தாள். காணாமல் போன பல்லாயிரம் பேரைப்போல அவளது மகள் காணவேயில்லை. மகளில்லாமல் அசையேன் என்ற அம்மாவை முகாம்வரை கொண்டு சேர்த்தும் மகளைத்தேடும் அம்மாவின் முயற்சியின் விளைவாக ஒற்றைக்காலை இழந்தபடி பெற்றோருடன் இணைந்தாள். தொடர் அலைவு துயரங்களின் முடிவாக மீண்டும் சொந்த ஊருக்குப்போயிருக்கும் குடும்பத்தின் நம்பிக்கையான மகள் தற்போது ஏ.எல்.உயர்தரம் விஞ்ஞானம் கற்கிறாள். எல்லாம் இழந்து தனது கல்வியை மட்டும் நம்பிய 17வயதுச்
வீட்டுக்கு எல்லாமுமாக இருந்த கணவனை 23.04.2009 அன்று எறிகணை கொன்றுவிட்டது. குடும்பத்தில் முதல் உயிரை இழந்த துயரம். எல்லொரையுமே துரத்தியது. உயிரைக்கொடுத்த துயரில் இருந்த வீட்டின் இரண்டு ஆண்பிள்ளைகளும் அம்மாவையும் தங்கைகளையும் விட்டுப் பிரிக்கப்பட்டார்கள். குடும்பத்தைத் தாங்குவார்கள் தன் மகள்களைக் காப்பாற்றுவார்கள் என்ற இரண்டு ஆண்பிள்ளைகளையும் கட்டாயக்களம் அழைத்துப் போனதோடு இந்தத்தாயின் எல்லா நம்பிக்கைகளும் நொருங்கிப்போனது. ஒருவன் இறந்து விட்டானென்ற செய்தியும் மற்றைய மகன் காணாமல் போனோர் வரிசையிலும் இன்னும் தேடப்பட்டுக் கொண்டிருக்கிறான்.
போரின் எச்சங்களாய் வன்னிநிலப்பகுதிகளில் மிஞ்சியிருப்பது துயரங்களின் குவியல். காலம்காலமாய் வாழ்ந்த மக்களின் நிலங்கள் பறிக்கப்பட்டு மனிதவுயிர்கள் எண்ணுக்கணக்கின்றி அழிக்கப்பட்ட கொடுமையின் முடிவு எங்கள் மக்களை ஏதிலிகளாக்கிவிட்டுள்ளது. தங்கள் நிலங்களில் மீளவும் வாழ வழியற்றுத் தவிக்கும் மனிதர்களும் அவர்களின் அனாதைக் குழந்தைகளும் தங்கள் எதிர்காலம் மீதான நம்பிக்கைகளுடன் தறப்பாள்களின

In [5]:
import os

file_path = "Tamil_Corpus_Cleaned.txt"
print("File exists:", os.path.exists(file_path))
print("File size:", os.path.getsize(file_path), "bytes")

File exists: True
File size: 5454682875 bytes

In [6]:
from datasets import load_dataset

dataset = load_dataset('text', data_files="Tamil_Corpus_Cleaned.txt", encoding="utf-8")

In [7]:
dataset['train']

Dataset({
    features: ['text'],
    num_rows: 6971580
})

In [14]:
from tqdm import tqdm
from transformers import BertTokenizerFast, AutoTokenizer
from datasets import load_dataset
import glob

#loading bert tokenizer to work as a base for the new tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

def batch_iterator(batch_size=10000):
    for i in tqdm(range(0, len(dataset['train']), batch_size)):
        yield dataset['train'][i: i +batch_size]['text']
bert_tokenizer = tokenizer.train_new_from_iterator(text_iterator=batch_iterator(), 
                                                   vocab_size=20000)
bert_tokenizer.save_pretrained('bert_wordpiece/')

100%|█████████████████████████████████████████████████████████████████████████████████| 698/698 [03:36<00:00,  3.23it/s]

('bert_wordpiece/tokenizer_config.json',
 'bert_wordpiece/special_tokens_map.json',
 'bert_wordpiece/vocab.txt',
 'bert_wordpiece/added_tokens.json',
 'bert_wordpiece/tokenizer.json')

In [ ]:
# cell-3
#tokenizing the whole text  

from datasets import load_dataset
import glob
import tokenizers
from transformers import Trainer, TrainingArguments, LineByLineTextDataset, BertModel
from transformers import BertConfig, BertForMaskedLM, DataCollatorForLanguageModeling
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert_wordpiece/')
max_seq_length = 64

dataset = load_dataset('text', data_files="Tamil_Corpus_Cleaned.txt", encoding="utf-8")

def encode_with_truncation(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length",
                   max_length=max_seq_length, return_special_tokens_mask=True)


dataset = dataset["train"].map(encode_with_truncation, batched=True)
dataset.set_format(type="torch", columns=["input_ids", "attention_mask"])

display(len(dataset))

In [ ]:
dataset.features

In [17]:
dataset = dataset.remove_columns(["text"])

In [18]:
dataset.save_to_disk("tokenized_dataset_wordpiece/dataset")

Saving the dataset (0/7 shards):   0%|          | 0/6971580 [00:00<?, ? examples/s]

In [19]:
#start here
from datasets import load_from_disk 
from datasets import load_dataset
import glob
import tokenizers
from transformers import Trainer, TrainingArguments, LineByLineTextDataset, BertModel
from transformers import BertConfig, BertForMaskedLM, DataCollatorForLanguageModeling
from transformers import AutoTokenizer

dataset = load_from_disk("tokenized_dataset_wordpiece/dataset")

In [20]:
# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert_wordpiece/')

# Model configuration optimized for efficiency
config = BertConfig(
    vocab_size=20000,  
    hidden_size=192,  
    num_hidden_layers=3,  
    num_attention_heads=3,  
    max_position_embeddings=64
)

# Initialize model
model = BertForMaskedLM(config)
print(f"Total Parameters: {model.num_parameters()}")

Total Parameters: 7906208

In [24]:
import glob
import tokenizers

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=True, mlm_probability=0.15)
epochs = 1
save_steps = 10000 #save checkpoint every 10000 steps
batch_size = 64

training_args = TrainingArguments(
    output_dir = 'bert_wordpiece/',
    overwrite_output_dir=True,
    num_train_epochs = epochs,
    per_device_train_batch_size = batch_size,
    save_steps = save_steps,
    save_total_limit = 2, #only save the last 5 checkpoints
    fp16=True,
    learning_rate = 1e-4,  # 5e-5 is the default
    logging_steps = 5_000,
    # gradient_accumulation_steps=4,
    # gradient_checkpointing=True
)
trainer = Trainer(
    model = model,
    args = training_args,
    data_collator=data_collator,
    train_dataset=dataset
)
# Train model
trainer.train()
# Save final model
trainer.save_model('bert_wordpiece/')

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

In [4]:
tamil_file = "cleaned_tamil_test.txt"

with open(tamil_file, encoding='utf-8') as f:  
    print(f.read(500))

கொண்டலாம்பட்டி
கொண்டலாம்பட்டி (ஆங்கிலம்:Kondalampatti), என்பது இந்தியாவின் தமிழ்நாடு மாநிலத்தில் அமைந்துள்ள சேலம் மாவட்டத்தில் இருக்கும் ஒரு கணக்கெடுப்பில் உள்ள ஊர் ஆகும்.
இந்திய 2001 மக்கள் தொகை கணக்கெடுப்பின்படி 16,300 மக்கள் இங்கு வசிக்கின்றார்கள். இவர்களில் 50% ஆண்கள், 50% பெண்கள் ஆவார்கள். கொண்டல்பட்டி மக்களின் சராசரி கல்வியறிவு 52% ஆகும், இதில் ஆண்களின் கல்வியறிவு 61%, பெண்களின் கல்வியறிவு 42% ஆகும். இது இந்திய தேசிய சராசரி கல்வியறிவான 59.5% விட குறைந்ததே. கொண்டல்பட்டி மக்கள் தொகையில் 13%

In [6]:
from transformers import BertTokenizer

def tokenize_text(file_path, model='bert_wordpiece/'):
    tokenizer = AutoTokenizer.from_pretrained(model)
    
    with open(file_path, 'r', encoding='utf-8') as file:
        text = file.read()
    
    tokens = tokenizer.tokenize(text)
    
    return tokens

tokenized_text = tokenize_text('cleaned_tamil_test.txt')

Token indices sequence length is longer than the specified maximum sequence length for this model (1612655 > 512). Running this sequence through the model will result in indexing errors

## Vocabualry 50000

In [8]:
from tqdm import tqdm
from transformers import BertTokenizerFast, AutoTokenizer
from datasets import load_dataset
import glob

#loading bert tokenizer to work as a base for the new tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

def batch_iterator(batch_size=10000):
    for i in tqdm(range(0, len(dataset['train']), batch_size)):
        yield dataset['train'][i: i +batch_size]['text']
bert_tokenizer = tokenizer.train_new_from_iterator(text_iterator=batch_iterator(), 
                                                   vocab_size=50000)
bert_tokenizer.save_pretrained('bert_wordpiece_50000/')

100%|█████████████████████████████████████████████████████████████████████████████████| 698/698 [02:48<00:00,  4.13it/s]

('bert_wordpiece_50000/tokenizer_config.json',
 'bert_wordpiece_50000/special_tokens_map.json',
 'bert_wordpiece_50000/vocab.txt',
 'bert_wordpiece_50000/added_tokens.json',
 'bert_wordpiece_50000/tokenizer.json')

In [11]:
# cell-3
#tokenizing the whole text  

from datasets import load_dataset
import glob
import tokenizers
from transformers import Trainer, TrainingArguments, LineByLineTextDataset, BertModel
from transformers import BertConfig, BertForMaskedLM, DataCollatorForLanguageModeling
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert_wordpiece_50000/')
max_seq_length = 64

dataset = load_dataset('text', data_files="Tamil_Corpus_Cleaned.txt", encoding="utf-8")

def encode_with_truncation(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length",
                   max_length=max_seq_length, return_special_tokens_mask=True)


dataset = dataset["train"].map(encode_with_truncation, batched=True)
dataset.set_format(type="torch", columns=["input_ids", "attention_mask"])

display(len(dataset))

Map:   0%|          | 0/6971580 [00:00<?, ? examples/s]

6971580

In [12]:
dataset.features

{'text': Value(dtype='string', id=None),
 'input_ids': Sequence(feature=Value(dtype='int32', id=None), length=-1, id=None),
 'token_type_ids': Sequence(feature=Value(dtype='int8', id=None), length=-1, id=None),
 'attention_mask': Sequence(feature=Value(dtype='int8', id=None), length=-1, id=None),
 'special_tokens_mask': Sequence(feature=Value(dtype='int8', id=None), length=-1, id=None)}

In [13]:
dataset = dataset.remove_columns(["text"])

In [14]:
dataset.save_to_disk("tokenized_dataset_wordpiece_50000/dataset")

Saving the dataset (0/7 shards):   0%|          | 0/6971580 [00:00<?, ? examples/s]

In [17]:
#start here

from datasets import load_from_disk 

from datasets import load_dataset
import glob
import tokenizers
from transformers import Trainer, TrainingArguments, LineByLineTextDataset, BertModel
from transformers import BertConfig, BertForMaskedLM, DataCollatorForLanguageModeling
from transformers import AutoTokenizer

dataset = load_from_disk("tokenized_dataset_wordpiece_50000/dataset")

In [18]:
# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert_wordpiece_50000/')

# Model configuration optimized for efficiency
config = BertConfig(
    vocab_size=50000,  
    hidden_size=192,  
    num_hidden_layers=3,  
    num_attention_heads=3,  
    max_position_embeddings=64
)

# Initialize model
model = BertForMaskedLM(config)
print(f"Total Parameters: {model.num_parameters()}")

Total Parameters: 13696208

In [19]:
import glob
import tokenizers

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=True,
                                               mlm_probability=0.15)
epochs = 1
save_steps = 10000 #save checkpoint every 10000 steps
batch_size = 64

training_args = TrainingArguments(
    output_dir = 'bert_wordpiece_50000/',
    overwrite_output_dir=True,
    num_train_epochs = epochs,
    per_device_train_batch_size = batch_size,
    save_steps = save_steps,
    save_total_limit = 2, #only save the last 5 checkpoints
    fp16=True,
    learning_rate = 1e-4,  # 5e-5 is the default
    logging_steps = 5_000,
    # gradient_accumulation_steps=4,
    # gradient_checkpointing=True
)

trainer = Trainer(
    model = model,
    args = training_args,
    data_collator=data_collator,
    train_dataset=dataset

)

# Train model
trainer.train()

# Save final model
trainer.save_model('bert_wordpiece_50000/')

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.